# https://blog.csdn.net/Draonly/article/details/125119683#t0
TebLocalPlannerROS:
  #*******************************************************************************
  # Trajectory
  #*******************************************************************************
  teb_autosize: True #优化期间允许改变轨迹的时域长度
  #TEB通过状态搜索树寻找最优路径，而dt_ref则是最优路径上的两个相邻姿态
  #（即位置、速度、航向信息，可通过TEB可视化在rivz中看到）的默认距离
  #此距离不固定，规划器自动根据速度大小调整这一距离，速度越大，相邻距离自然越大，
  #较小的值理论上可提供更高精度
  dt_ref: 0.5               #局部路径规划的解析度
  dt_hysteresis: 0.1        #允许改变的时域解析度的浮动范围， 一般为 dt_ref 的 10% 左右;
  max_samples: 500          #
  global_plan_overwrite_orientation: True      #覆盖全局路径中局部路径点的朝向
  allow_init_with_backwards_motion: False      #允许在开始时想后退来执行轨迹
  #考虑优化的全局计划子集的最大长度（累积欧几里得距离）
  #如果为0或负数：禁用；长度也受本地Costmap大小的限制
  max_global_plan_lookahead_dist: 1.5
  global_plan_viapoint_sep: -1  #从全局路径中选取的每两个连续通过点之间的最小间隔
  global_plan_prune_distance: 1  #该参数决定了从机器人当前位置的后面一定距离开始裁剪
  #如果为真，规划器在速度、加速度和转弯率计算中使用精确的弧长[增加的CPU时间]，否则使用欧几里德近似。
  exact_arc_length: False
  #在判断生成的轨迹是否冲突时使用，此时设置为3，即从轨迹起点开始逐个检查轨迹上的3个点，
  #若3个点均不发生碰撞，则认为本次轨迹有效。若小于0则检查所有路径点
  feasibility_check_no_poses: 5   #检测位姿可到达的时间间隔
  publish_feedback: False        #发布包含完整轨迹和活动障碍物列表的规划器反馈

  #*******************************************************************************
  # Robot
  #*******************************************************************************
  max_vel_x: 3.0             #最大x前向速度
  max_vel_x_backwards: 3.0   #最大x后退速度
  max_vel_y: 3.0             #最大y方向速度
  #  max_vel_y_backwards: 1.0   #最大x后退速度
  max_vel_theta: 6.28        #最大转向角速度
  max_vel_theta_backwards: 6.28        #最大转向角速度
  acc_lim_x: 2.5             #最大x加速度
  acc_lim_y: 2.5             #最大x加速度
  acc_lim_theta: 6.28        #最大角加速度
  min_turning_radius: 0.0    #车类机器人的最小转弯半径的角速度消息转换为 操作上的角度变化
  # types: "point", "circular", "two_circles", "line", "polygon"
  footprint_model:
    type: "polygon"    #多边形
    vertices: [ [ -0.25, -0.25 ], [ 0.25, -0.25 ], [ 0.25, 0.25 ], [ -0.25, 0.25 ] ]
  #    type: "circular"   #圆
  #    radius: 0.31 # for type "circular"

  #*******************************************************************************
  # GoalTolerance
  #*******************************************************************************
  xy_goal_tolerance: 0.15   #目标 xy 偏移容忍度
  yaw_goal_tolerance: 0.1   #目标 角度 偏移容忍度
  free_goal_vel: false      #允许机器人以最大速度驶向目的地，为False时，车到达终点时的目标速度为0；
  #  complete_global_plan: True

  #*******************************************************************************
  # Obstacles
  #*******************************************************************************
  min_obstacle_dist: 0.4                     #和障碍物最小距离
  inflation_dist: 0.5                         #障碍物膨胀距离
  include_costmap_obstacles: True             #costmap 中的障碍物是否被直接考虑
  costmap_obstacles_behind_robot_dist: 2.0    #规划时考虑后面n米内的障碍物
  obstacle_poses_affected: 10                 #障碍物姿态受影响程度0-30

  dynamic_obstacle_inflation_dist: 0.5      #动态障碍物的膨胀范围
  include_dynamic_obstacles: False          #是否将动态障碍物预测为速度模型


  #*******************************************************************************
  # Optimization
  #*******************************************************************************
  no_inner_iterations: 5         #被外循环调用后内循环执行优化次数
  no_outer_iterations: 4         #执行的外循环的优化次数执行的外循环的优化次数
  optimization_activate: True    #激活优化
  optimization_verbose: False    #打印优化过程详情
  penalty_epsilon: 0.1           #对于硬约束近似，在惩罚函数中添加安全范围
  obstacle_cost_exponent: 4
  weight_max_vel_x: 2            #最大x速度权重 0~2
  weight_max_vel_y: 2            #最大x速度权重 0~2
  weight_max_vel_theta: 1        #最大角速度权重 0~1
  weight_acc_lim_x: 1            #最大x 加速度权重 0~1
  weight_acc_lim_y: 1            #最大x 加速度权重 0~1
  weight_acc_lim_theta: 1        #最大角速度权重 0~1
  weight_kinematics_nh: 1     #非完整运动学的优化权重
  weight_kinematics_forward_drive: 0     #优化过程中，迫使机器人只选择前进方向，差速轮适用
  weight_kinematics_turning_radius: 0    #优化过程中，车型机器人的最小转弯半径的权重
  weight_optimaltime: 1000 # must be > 0  #优化过程中，基于轨迹的时间上的权重
  weight_shortest_path: 50
  weight_obstacle: 500           #优化过程中，和障碍物最小距离的权重 0~50
  weight_inflation: 5.0          #优化过程中， 膨胀区的权重
  weight_dynamic_obstacle: 10    #优化过程中，和动态障碍物最小距离的权重
  weight_dynamic_obstacle_inflation: 0.2  #优化过程中，和动态障碍物膨胀区的权重 0~50
  weight_viapoint: 50             #优化过程中，和全局路径采样点距离的权重

  map_frame: "/map"

